# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.kairos:
        class: WhosThatIdolBundle\Service\Kairos
        arguments: ['%kairos_app_id%', '%kairos_app_key%']

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
